### ISSUE TITLE
Parameter strictness

### ISSUE THREAD

**Issue by adam-dempsey** [lozalojo/memapp#6] opened 2023-10-17 08:21 UTC
Hi,

I was wondering whether the mem package could be used to measure epidemic intensity for parameters other than ILI (i.e., acute respiratory infection presentations per 100,000) instead?  Is the model strict on the use of ILI?

I have tried with 5 seasons of ARI data but have the (attached) issue of the baseline threshold being higher than the medium intensity threshold.

Any guidance would be appreciated!

![mem snip](https://github.com/lozalojo/memapp/assets/148196867/25d54086-c459-4942-94e5-17128f7fa57c)

**Comment by lozalojo** [comment] 2023-10-17 10:49
Hi,

mem has been extensively used with other parameters, our paper on intensity levels (DOI:10.1111/irv.12330) contains ARI and %consultation datasets, but we've used it for Covid rates, hospital admissions or % positive to flu.

Your problem with threshold higher than medium intensity level is known among ARI data. The problem is that there is always a pre-epidemic wave prior the main epidemic, this forces the threshold to be higher than normal to sort out this previous epidemic.

The solution is more conceptual than technical: do you want to "detect" also this previous epidemic? Then use the "Two-waves" algorithm of memapp to separate first and second wave of each season, and then apply mem to first ones, to second ones or to all of them pooled together. If you don’t want to give the signal alert on the first wave and just detect the second one (this is the context of Flu, since the first wave might be associated with RSV and the second one with Flu), then let the threshold as it is and ignore the problem with medium intensity.

**Comment by adam-dempsey** [comment] 2023-10-23 08:08
Brilliant, thanks so much - that's extremely helpful.  I will use the two-waves algorithm on the current dataset to solve the issue.

Thanks again - appreciate the help!

**Comment by lozalojo** [comment] 2023-10-23 09:08
I close the issue, then, thanks!

**Closed as completed by lozalojo** 2023-10-23 09:08 UTC
